name: Validating SUIT Encrypted Payloads examples
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install cbor-diag cddl
    - uses: actions/setup-python@v4
    - run: python -m pip install cwt>=2.7.0
    - run: sudo apt-get update && sudo apt-get install -y xxd
    - name: Vaildate examples
      run: make -C examples/ validate
